/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uas_restoran;

import java.awt.Desktop;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ritz
 */
public class Pembayaran
        extends javax.swing.JFrame {
    int bayar;
    int kembali;
    int total;


    /**
     * Creates new form Struk
     */
    public Pembayaran() {
        initComponents();
        loadData();
    }
    
    public final void loadData() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT SUM(total_harga) as total FROM temp_penjualan";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                txt_total.setText(r.getString("total"));
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("line 92: "+ e);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txt_total = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_selesai = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_pembayaran = new javax.swing.JComboBox<>();
        txt_customer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_total.setText("Rp. ");

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bayarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Bayar");

        txt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembalianActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Kembalian");

        btn_selesai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_selesai.setText("Selesai Transaksi");
        btn_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selesaiActionPerformed(evt);
            }
        });

        btn_cetak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cetak.setText("Cetak Struk");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Pembayaran");

        cb_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembayaran", "Tunai", "Debit", "QRIS" }));

        txt_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_customerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nama Kostumer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kembalian)
                            .addComponent(txt_bayar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_pembayaran, 0, 199, Short.MAX_VALUE)
                            .addComponent(txt_customer))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_selesai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cetak)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
        bayar = Integer.parseInt(String.valueOf(txt_bayar.getText()));
        total = Integer.parseInt(String.valueOf(txt_total.getText()));
        kembali = bayar - total;

        txt_kembalian.setText(Long.toString(kembali));
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void txt_bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyTyped
        // TODO add your handling code here:
        Config.FilterAngka(evt);
    }//GEN-LAST:event_txt_bayarKeyTyped

    private void txt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianActionPerformed

    private void btn_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selesaiActionPerformed
        // TODO add your handling code here:
        if(txt_bayar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "Restoran",
                JOptionPane.INFORMATION_MESSAGE);

        } else {
            String a = txt_kembalian.getText();
            int ab = Integer.parseInt(String.valueOf(txt_kembalian.getText()));
            if(ab < 0){
                JOptionPane.showMessageDialog(null, "Uang anda kurang", "Aplikasi Penjualan",
                    JOptionPane.INFORMATION_MESSAGE);
                txt_bayar.setText("");
                txt_kembalian.setText("");
            }else{
                try {
                    Connection c = Koneksi.getKoneksi();
                    Statement s = c.createStatement();
                    String id_transaksi = null;

                    long millis=System.currentTimeMillis();
                    java.sql.Date date=new java.sql.Date(millis);
                    System.out.println(date);
                    String tgl = date.toString();
                    String sqlTransaksi = "INSERT INTO transaksi VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                    Config config = new Config();
                    
                    PreparedStatement p = c.prepareStatement(sqlTransaksi);
                    p.setString(1, null);
                    p.setString(2, tgl);
                    p.setString(3, txt_customer.getText());
                    p.setString(4, String.valueOf(total));
                    p.setString(5, (String) cb_pembayaran.getSelectedItem());
                    p.setString(6, "agung");
                    p.setString(7, txt_bayar.getText());
                    p.setString(8, txt_kembalian.getText());

                    
                    p.executeUpdate();
                    
                    try {
                        String sqlDetail = "SELECT * FROM transaksi ORDER BY id_transaksi DESC LIMIT 1 ";
                        ResultSet response = s.executeQuery(sqlDetail);
                        if(response.next()){
                            id_transaksi = response.getString("id_transaksi");
                        }
                        response.close();
                    }catch(Exception e){
                        System.out.println("line: "+ e);
                    }
                    
                    try {
                        String sql = "SELECT * FROM temp_penjualan";
                        Connection con = Koneksi.getKoneksi();
                        Statement state = con.createStatement();
                        ResultSet r = state.executeQuery(sql);
                        while (r.next()) {
                           
                            String sqlInputDetail = "INSERT INTO detail_transaksi VALUES (?, ?, ?, ?, ?)";
                            PreparedStatement inputDetail = con.prepareStatement(sqlInputDetail);
                            inputDetail.setString(1, r.getString("nama_menu"));
                            inputDetail.setString(2, r.getString("jumlah_beli"));
                            inputDetail.setString(3, id_transaksi);
                            inputDetail.setString(4, null);
                            inputDetail.setString(5, r.getString("total_harga"));

                            inputDetail.executeUpdate();
                            System.out.println("response2: "+ r.getString("nama_menu"));

                        }
                        id_transaksi = null;
                        p.close();
                        s.close();
                        r.close();
                        state.close();
                    }catch(Exception e){
                        System.out.println("line: "+ e);
                    }
                    try {
                        String sqla ="TRUNCATE temp_penjualan";
                        Connection conn= Koneksi.getKoneksi();
                        PreparedStatement pst= conn.prepareStatement(sqla);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "TRANSAKSI SELESAI", "Restoran",
                            JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                } catch (SQLException e) {
                    System.out.println("line 614: "+ e);
                }
            }
        }
    }//GEN-LAST:event_btn_selesaiActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try{
            String id_transaksi = null;

            try {
                String sqlDetail = "SELECT * FROM transaksi ORDER BY id_transaksi DESC LIMIT 1 ";
                Connection c = Koneksi.getKoneksi();
                Statement s = c.createStatement();
                ResultSet response = s.executeQuery(sqlDetail);
                if(response.next()){
                    id_transaksi = response.getString("id_transaksi");
                }
                response.close();
            }catch(Exception e){
                System.out.println("line: "+ e);
            }
            Desktop.getDesktop().browse(new
                URL("http://localhost/restoran/invoice.php?lap&id="+ id_transaksi ).toURI());
            Transaksi tr = new Transaksi();
                        tr.setVisible(true);
                        this.setVisible(false);
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_selesai;
    private javax.swing.JComboBox<String> cb_pembayaran;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_customer;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
